/**
 * Build Cloudflare Pages redirects for old year-suffixed value URLs.
 * Run before astro build (also safe to run alone).
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const YEAR = /\s+(19|20)\d{2}\s*$/

function stripYear(name) {
  return name.replace(YEAR, '').trim()
}

function slugify(name) {
  return name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function shortId(id) {
  return String(id).replace(/[^a-z0-9]/gi, '').slice(-6).toLowerCase() || 'item'
}

function loadRows() {
  const items = JSON.parse(fs.readFileSync(path.join(ROOT, 'src/data/items.json'), 'utf8')).items
  const sets = JSON.parse(fs.readFileSync(path.join(ROOT, 'src/data/sets.json'), 'utf8')).sets || []
  return [...items, ...sets]
}

function build() {
  const rows = loadRows()
  const names = rows.map((r) => r.name)
  const used = new Map()
  const lines = [
    '# Auto-generated — old year URLs → clean value pages',
    '# Do not edit by hand; regenerated by scripts/write_value_redirects.mjs',
  ]

  const redirects = new Map()

  for (const item of rows) {
    const baseName = stripYear(item.name)
    const collisions = names.filter((n) => stripYear(n).toLowerCase() === baseName.toLowerCase())
    const display = collisions.length <= 1 ? baseName || item.name : item.name
    let base = slugify(display) || `item-${shortId(item.id)}`
    const seen = used.get(base) || 0
    used.set(base, seen + 1)
    const slug = seen === 0 ? base : `${base}-${shortId(item.id)}`

    for (const from of [slugify(item.id), slugify(item.name)]) {
      if (from && from !== slug && !redirects.has(from)) {
        redirects.set(from, slug)
      }
    }
  }

  for (const [from, to] of redirects) {
    lines.push(`/values/${from}/ /values/${to}/ 301`)
    lines.push(`/values/${from} /values/${to}/ 301`)
  }

  const out = path.join(ROOT, 'public', '_redirects')
  // Keep any non-value redirects if we add them later — for now overwrite with generated + note
  const existing = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : ''
  const manual = existing
    .split(/\r?\n/)
    .filter((l) => l && !l.includes('/values/') && !l.startsWith('# Auto-generated'))
  const body = [...manual, ...lines].join('\n') + '\n'
  fs.writeFileSync(out, body)
  console.log(`Wrote ${redirects.size * 2} value redirect rules → public/_redirects`)
}

build()
